# Pull Geth into a second stage deploy alpine container
ARG ethmonitor_port
ARG analyzer_port
ARG ethmonitor_controller
ARG verbosity="3"
FROM alpine:latest
ARG ethmonitor_port
ARG analyzer_port
ARG ethmonitor_controller
ARG verbosity="3"

ENV e_port=$ethmonitor_port
ENV a_port=$ethmonitor_portd
ENV e_controller=$ethmonitor_controller
ENV v=$verbosity

RUN apk add --no-cache ca-certificates
COPY --from=darcher/go-ethereum/executables /darcher-go-ethereum/build/bin/ethmonitor /usr/local/bin/
EXPOSE $e_port $a_port
ENTRYPOINT ethmonitor --ethmonitor.port $e_port --ethmonitor.controller $e_controller --analyzer.port $a_port --verbosity $v
