// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: common.proto

package rpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Role int32

const (
	Role_DOER      Role = 0
	Role_TALKER    Role = 1
	Role_DAPP      Role = 2
	Role_DBMONITOR Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "DOER",
		1: "TALKER",
		2: "DAPP",
		3: "DBMONITOR",
	}
	Role_value = map[string]int32{
		"DOER":      0,
		"TALKER":    1,
		"DAPP":      2,
		"DBMONITOR": 3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type Error int32

const (
	Error_NilErr                 Error = 0
	Error_InternalErr            Error = 1
	Error_TimeoutErr             Error = 2
	Error_ServiceNotAvailableErr Error = 3
)

// Enum value maps for Error.
var (
	Error_name = map[int32]string{
		0: "NilErr",
		1: "InternalErr",
		2: "TimeoutErr",
		3: "ServiceNotAvailableErr",
	}
	Error_value = map[string]int32{
		"NilErr":                 0,
		"InternalErr":            1,
		"TimeoutErr":             2,
		"ServiceNotAvailableErr": 3,
	}
)

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}

func (x Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (Error) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error.Descriptor instead.
func (Error) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type TxState int32

const (
	TxState_CREATED   TxState = 0
	TxState_PENDING   TxState = 1
	TxState_EXECUTED  TxState = 2
	TxState_DROPPED   TxState = 3
	TxState_CONFIRMED TxState = 4
)

// Enum value maps for TxState.
var (
	TxState_name = map[int32]string{
		0: "CREATED",
		1: "PENDING",
		2: "EXECUTED",
		3: "DROPPED",
		4: "CONFIRMED",
	}
	TxState_value = map[string]int32{
		"CREATED":   0,
		"PENDING":   1,
		"EXECUTED":  2,
		"DROPPED":   3,
		"CONFIRMED": 4,
	}
)

func (x TxState) Enum() *TxState {
	p := new(TxState)
	*p = x
	return p
}

func (x TxState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (TxState) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x TxState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxState.Descriptor instead.
func (TxState) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

//*
//TxError refers to errors that make transaction cannot be mined, or transaction is reverted due to internal errors in smart contract.
type TxErrorType int32

const (
	TxErrorType_NIL_TxErr TxErrorType = 0 // nil type, should not be used.
	TxErrorType_REVERT    TxErrorType = 1 // internal error in smart contract occurs, transaction is reverted
	TxErrorType_REJECT    TxErrorType = 2 // bad transaction which cannot be mined and rejected by evm
)

// Enum value maps for TxErrorType.
var (
	TxErrorType_name = map[int32]string{
		0: "NIL_TxErr",
		1: "REVERT",
		2: "REJECT",
	}
	TxErrorType_value = map[string]int32{
		"NIL_TxErr": 0,
		"REVERT":    1,
		"REJECT":    2,
	}
)

func (x TxErrorType) Enum() *TxErrorType {
	p := new(TxErrorType)
	*p = x
	return p
}

func (x TxErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[3].Descriptor()
}

func (TxErrorType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[3]
}

func (x TxErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxErrorType.Descriptor instead.
func (TxErrorType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

type TxErrorMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash        string      `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Type        TxErrorType `protobuf:"varint,2,opt,name=type,proto3,enum=darcher.TxErrorType" json:"type,omitempty"`
	Description string      `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *TxErrorMsg) Reset() {
	*x = TxErrorMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxErrorMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxErrorMsg) ProtoMessage() {}

func (x *TxErrorMsg) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxErrorMsg.ProtoReflect.Descriptor instead.
func (*TxErrorMsg) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *TxErrorMsg) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *TxErrorMsg) GetType() TxErrorType {
	if x != nil {
		return x.Type
	}
	return TxErrorType_NIL_TxErr
}

func (x *TxErrorMsg) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x64, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x22, 0x6c, 0x0a, 0x0a, 0x54, 0x78, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x72, 0x63, 0x68, 0x65,
	0x72, 0x2e, 0x54, 0x78, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x35, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x08, 0x0a,
	0x04, 0x44, 0x4f, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x41, 0x4c, 0x4b, 0x45,
	0x52, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x41, 0x50, 0x50, 0x10, 0x02, 0x12, 0x0d, 0x0a,
	0x09, 0x44, 0x42, 0x4d, 0x4f, 0x4e, 0x49, 0x54, 0x4f, 0x52, 0x10, 0x03, 0x2a, 0x50, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x69, 0x6c, 0x45, 0x72, 0x72, 0x10,
	0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x72, 0x72,
	0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x45, 0x72, 0x72,
	0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x6f, 0x74,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x45, 0x72, 0x72, 0x10, 0x03, 0x2a, 0x4d,
	0x0a, 0x07, 0x54, 0x78, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x52, 0x45,
	0x41, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e,
	0x47, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x58, 0x45, 0x43, 0x55, 0x54, 0x45, 0x44, 0x10,
	0x02, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x52, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0d,
	0x0a, 0x09, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x52, 0x4d, 0x45, 0x44, 0x10, 0x04, 0x2a, 0x34, 0x0a,
	0x0b, 0x54, 0x78, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09,
	0x4e, 0x49, 0x4c, 0x5f, 0x54, 0x78, 0x45, 0x72, 0x72, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x52,
	0x45, 0x56, 0x45, 0x52, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x4a, 0x45, 0x43,
	0x54, 0x10, 0x02, 0x42, 0x51, 0x0a, 0x17, 0x6f, 0x72, 0x67, 0x2e, 0x6b, 0x72, 0x69, 0x73, 0x74,
	0x65, 0x6e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x64, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x5a, 0x36,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x72, 0x6f, 0x75, 0x62,
	0x6c, 0x6f, 0x72, 0x2f, 0x64, 0x61, 0x72, 0x63, 0x68, 0x65, 0x72, 0x2d, 0x67, 0x6f, 0x2d, 0x65,
	0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2f, 0x65, 0x74, 0x68, 0x6d, 0x6f, 0x6e, 0x69, 0x74,
	0x6f, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_proto_goTypes = []interface{}{
	(Role)(0),          // 0: darcher.Role
	(Error)(0),         // 1: darcher.Error
	(TxState)(0),       // 2: darcher.TxState
	(TxErrorType)(0),   // 3: darcher.TxErrorType
	(*TxErrorMsg)(nil), // 4: darcher.TxErrorMsg
}
var file_common_proto_depIdxs = []int32{
	3, // 0: darcher.TxErrorMsg.type:type_name -> darcher.TxErrorType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxErrorMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
